//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("mn-mssql01")]
        public string SqlServer {
            get {
                return ((string)(this["SqlServer"]));
            }
            set {
                this["SqlServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1433")]
        public string SqlPort {
            get {
                return ((string)(this["SqlPort"]));
            }
            set {
                this["SqlPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("to_cdw@codeworks.by")]
        public string Email {
            get {
                return ((string)(this["Email"]));
            }
            set {
                this["Email"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ImgPath {
            get {
                return ((string)(this["ImgPath"]));
            }
            set {
                this["ImgPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TestDB")]
        public string SqlDataBase {
            get {
                return ((string)(this["SqlDataBase"]));
            }
            set {
                this["SqlDataBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int int_navigation {
            get {
                return ((int)(this["int_navigation"]));
            }
            set {
                this["int_navigation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int inr_barcod {
            get {
                return ((int)(this["inr_barcod"]));
            }
            set {
                this["inr_barcod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_mainTB_date {
            get {
                return ((bool)(this["mainForms_mainTB_date"]));
            }
            set {
                this["mainForms_mainTB_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mainForms_mainTB_TypeAC {
            get {
                return ((bool)(this["mainForms_mainTB_TypeAC"]));
            }
            set {
                this["mainForms_mainTB_TypeAC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_mainTB_InvNum {
            get {
                return ((bool)(this["mainForms_mainTB_InvNum"]));
            }
            set {
                this["mainForms_mainTB_InvNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_mainTB_LanName {
            get {
                return ((bool)(this["mainForms_mainTB_LanName"]));
            }
            set {
                this["mainForms_mainTB_LanName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_mainTB_ResName {
            get {
                return ((bool)(this["mainForms_mainTB_ResName"]));
            }
            set {
                this["mainForms_mainTB_ResName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_mainTB_Room {
            get {
                return ((bool)(this["mainForms_mainTB_Room"]));
            }
            set {
                this["mainForms_mainTB_Room"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_mainTB_Floor {
            get {
                return ((bool)(this["mainForms_mainTB_Floor"]));
            }
            set {
                this["mainForms_mainTB_Floor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_mainTB_TypeDiv {
            get {
                return ((bool)(this["mainForms_mainTB_TypeDiv"]));
            }
            set {
                this["mainForms_mainTB_TypeDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_mainTB_SN {
            get {
                return ((bool)(this["mainForms_mainTB_SN"]));
            }
            set {
                this["mainForms_mainTB_SN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_mainTB_Model {
            get {
                return ((bool)(this["mainForms_mainTB_Model"]));
            }
            set {
                this["mainForms_mainTB_Model"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mainForms_mainTB_WrittenOff {
            get {
                return ((bool)(this["mainForms_mainTB_WrittenOff"]));
            }
            set {
                this["mainForms_mainTB_WrittenOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_mainTB_JiraTask {
            get {
                return ((bool)(this["mainForms_mainTB_JiraTask"]));
            }
            set {
                this["mainForms_mainTB_JiraTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mainForms_mainTB_Reason {
            get {
                return ((bool)(this["mainForms_mainTB_Reason"]));
            }
            set {
                this["mainForms_mainTB_Reason"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_hardware_date {
            get {
                return ((bool)(this["mainForms_hardware_date"]));
            }
            set {
                this["mainForms_hardware_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mainForms_hardware_InvNum {
            get {
                return ((bool)(this["mainForms_hardware_InvNum"]));
            }
            set {
                this["mainForms_hardware_InvNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mainForms_hardware_LanName {
            get {
                return ((bool)(this["mainForms_hardware_LanName"]));
            }
            set {
                this["mainForms_hardware_LanName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mainForms_hardware_ResName {
            get {
                return ((bool)(this["mainForms_hardware_ResName"]));
            }
            set {
                this["mainForms_hardware_ResName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_hardware_Room {
            get {
                return ((bool)(this["mainForms_hardware_Room"]));
            }
            set {
                this["mainForms_hardware_Room"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mainForms_hardware_Floor {
            get {
                return ((bool)(this["mainForms_hardware_Floor"]));
            }
            set {
                this["mainForms_hardware_Floor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_hardware_TypeDiv {
            get {
                return ((bool)(this["mainForms_hardware_TypeDiv"]));
            }
            set {
                this["mainForms_hardware_TypeDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mainForms_hardware_SN {
            get {
                return ((bool)(this["mainForms_hardware_SN"]));
            }
            set {
                this["mainForms_hardware_SN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_hardware_Model {
            get {
                return ((bool)(this["mainForms_hardware_Model"]));
            }
            set {
                this["mainForms_hardware_Model"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_hardware_WrittenOff {
            get {
                return ((bool)(this["mainForms_hardware_WrittenOff"]));
            }
            set {
                this["mainForms_hardware_WrittenOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mainForms_hardware_JiraTask {
            get {
                return ((bool)(this["mainForms_hardware_JiraTask"]));
            }
            set {
                this["mainForms_hardware_JiraTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mainForms_hardware_Reason {
            get {
                return ((bool)(this["mainForms_hardware_Reason"]));
            }
            set {
                this["mainForms_hardware_Reason"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mainForms_hardware_ID {
            get {
                return ((bool)(this["mainForms_hardware_ID"]));
            }
            set {
                this["mainForms_hardware_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mainForms_mainTB_ID {
            get {
                return ((bool)(this["mainForms_mainTB_ID"]));
            }
            set {
                this["mainForms_mainTB_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mainForms_stockroom_ID {
            get {
                return ((bool)(this["mainForms_stockroom_ID"]));
            }
            set {
                this["mainForms_stockroom_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_stockroom_date {
            get {
                return ((bool)(this["mainForms_stockroom_date"]));
            }
            set {
                this["mainForms_stockroom_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_stockroom_InvNum {
            get {
                return ((bool)(this["mainForms_stockroom_InvNum"]));
            }
            set {
                this["mainForms_stockroom_InvNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_stockroom_TypeDiv {
            get {
                return ((bool)(this["mainForms_stockroom_TypeDiv"]));
            }
            set {
                this["mainForms_stockroom_TypeDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_stockroom_Quantity {
            get {
                return ((bool)(this["mainForms_stockroom_Quantity"]));
            }
            set {
                this["mainForms_stockroom_Quantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_stockroom_SN {
            get {
                return ((bool)(this["mainForms_stockroom_SN"]));
            }
            set {
                this["mainForms_stockroom_SN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_stockroom_Model {
            get {
                return ((bool)(this["mainForms_stockroom_Model"]));
            }
            set {
                this["mainForms_stockroom_Model"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mainForms_stockroom_WrittenOff {
            get {
                return ((bool)(this["mainForms_stockroom_WrittenOff"]));
            }
            set {
                this["mainForms_stockroom_WrittenOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool mainForms_stockroom_JiraTask {
            get {
                return ((bool)(this["mainForms_stockroom_JiraTask"]));
            }
            set {
                this["mainForms_stockroom_JiraTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool mainForms_stockroom_Reason {
            get {
                return ((bool)(this["mainForms_stockroom_Reason"]));
            }
            set {
                this["mainForms_stockroom_Reason"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setDataBase_mainTB_ID {
            get {
                return ((bool)(this["setDataBase_mainTB_ID"]));
            }
            set {
                this["setDataBase_mainTB_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setDataBase_mainTB_date {
            get {
                return ((bool)(this["setDataBase_mainTB_date"]));
            }
            set {
                this["setDataBase_mainTB_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setDataBase_mainTB_TypeAC {
            get {
                return ((bool)(this["setDataBase_mainTB_TypeAC"]));
            }
            set {
                this["setDataBase_mainTB_TypeAC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setDataBase_mainTB_InvNum {
            get {
                return ((bool)(this["setDataBase_mainTB_InvNum"]));
            }
            set {
                this["setDataBase_mainTB_InvNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setDataBase_mainTB_LanName {
            get {
                return ((bool)(this["setDataBase_mainTB_LanName"]));
            }
            set {
                this["setDataBase_mainTB_LanName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setDataBase_mainTB_ResName {
            get {
                return ((bool)(this["setDataBase_mainTB_ResName"]));
            }
            set {
                this["setDataBase_mainTB_ResName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setDataBase_mainTB_Room {
            get {
                return ((bool)(this["setDataBase_mainTB_Room"]));
            }
            set {
                this["setDataBase_mainTB_Room"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setDataBase_mainTB_Floor {
            get {
                return ((bool)(this["setDataBase_mainTB_Floor"]));
            }
            set {
                this["setDataBase_mainTB_Floor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setDataBase_mainTB_TypeDiv {
            get {
                return ((bool)(this["setDataBase_mainTB_TypeDiv"]));
            }
            set {
                this["setDataBase_mainTB_TypeDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setDataBase_mainTB_SN {
            get {
                return ((bool)(this["setDataBase_mainTB_SN"]));
            }
            set {
                this["setDataBase_mainTB_SN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setDataBase_mainTB_Model {
            get {
                return ((bool)(this["setDataBase_mainTB_Model"]));
            }
            set {
                this["setDataBase_mainTB_Model"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setDataBase_mainTB_WrittenOff {
            get {
                return ((bool)(this["setDataBase_mainTB_WrittenOff"]));
            }
            set {
                this["setDataBase_mainTB_WrittenOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setDataBase_mainTB_JiraTask {
            get {
                return ((bool)(this["setDataBase_mainTB_JiraTask"]));
            }
            set {
                this["setDataBase_mainTB_JiraTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setDataBase_mainTB_Reason {
            get {
                return ((bool)(this["setDataBase_mainTB_Reason"]));
            }
            set {
                this["setDataBase_mainTB_Reason"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int print_name_or_model {
            get {
                return ((int)(this["print_name_or_model"]));
            }
            set {
                this["print_name_or_model"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool changeFormTwo_mainTB_ID {
            get {
                return ((bool)(this["changeFormTwo_mainTB_ID"]));
            }
            set {
                this["changeFormTwo_mainTB_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool changeFormTwo_mainTB_date {
            get {
                return ((bool)(this["changeFormTwo_mainTB_date"]));
            }
            set {
                this["changeFormTwo_mainTB_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool changeFormTwo_mainTB_TypeAC {
            get {
                return ((bool)(this["changeFormTwo_mainTB_TypeAC"]));
            }
            set {
                this["changeFormTwo_mainTB_TypeAC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool changeFormTwo_mainTB_InvNum {
            get {
                return ((bool)(this["changeFormTwo_mainTB_InvNum"]));
            }
            set {
                this["changeFormTwo_mainTB_InvNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool changeFormTwo_mainTB_LanName {
            get {
                return ((bool)(this["changeFormTwo_mainTB_LanName"]));
            }
            set {
                this["changeFormTwo_mainTB_LanName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool changeFormTwo_mainTB_ResName {
            get {
                return ((bool)(this["changeFormTwo_mainTB_ResName"]));
            }
            set {
                this["changeFormTwo_mainTB_ResName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool changeFormTwo_mainTB_Room {
            get {
                return ((bool)(this["changeFormTwo_mainTB_Room"]));
            }
            set {
                this["changeFormTwo_mainTB_Room"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool changeFormTwo_mainTB_Floor {
            get {
                return ((bool)(this["changeFormTwo_mainTB_Floor"]));
            }
            set {
                this["changeFormTwo_mainTB_Floor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool changeFormTwo_mainTB_TypeDiv {
            get {
                return ((bool)(this["changeFormTwo_mainTB_TypeDiv"]));
            }
            set {
                this["changeFormTwo_mainTB_TypeDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool changeFormTwo_mainTB_SN {
            get {
                return ((bool)(this["changeFormTwo_mainTB_SN"]));
            }
            set {
                this["changeFormTwo_mainTB_SN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool changeFormTwo_mainTB_Model {
            get {
                return ((bool)(this["changeFormTwo_mainTB_Model"]));
            }
            set {
                this["changeFormTwo_mainTB_Model"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool changeFormTwo_mainTB_WrittenOff {
            get {
                return ((bool)(this["changeFormTwo_mainTB_WrittenOff"]));
            }
            set {
                this["changeFormTwo_mainTB_WrittenOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool changeFormTwo_mainTB_JiraTask {
            get {
                return ((bool)(this["changeFormTwo_mainTB_JiraTask"]));
            }
            set {
                this["changeFormTwo_mainTB_JiraTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool changeFormTwo_mainTB_Reason {
            get {
                return ((bool)(this["changeFormTwo_mainTB_Reason"]));
            }
            set {
                this["changeFormTwo_mainTB_Reason"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Search_hardware_ID {
            get {
                return ((bool)(this["Search_hardware_ID"]));
            }
            set {
                this["Search_hardware_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Search_hardware_date {
            get {
                return ((bool)(this["Search_hardware_date"]));
            }
            set {
                this["Search_hardware_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_hardware_InvNum {
            get {
                return ((bool)(this["Search_hardware_InvNum"]));
            }
            set {
                this["Search_hardware_InvNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_hardware_LanName {
            get {
                return ((bool)(this["Search_hardware_LanName"]));
            }
            set {
                this["Search_hardware_LanName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_hardware_ResName {
            get {
                return ((bool)(this["Search_hardware_ResName"]));
            }
            set {
                this["Search_hardware_ResName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_hardware_Room {
            get {
                return ((bool)(this["Search_hardware_Room"]));
            }
            set {
                this["Search_hardware_Room"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Search_hardware_Floor {
            get {
                return ((bool)(this["Search_hardware_Floor"]));
            }
            set {
                this["Search_hardware_Floor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_hardware_TypeDiv {
            get {
                return ((bool)(this["Search_hardware_TypeDiv"]));
            }
            set {
                this["Search_hardware_TypeDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_hardware_SN {
            get {
                return ((bool)(this["Search_hardware_SN"]));
            }
            set {
                this["Search_hardware_SN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_hardware_Model {
            get {
                return ((bool)(this["Search_hardware_Model"]));
            }
            set {
                this["Search_hardware_Model"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Search_hardware_WrittenOff {
            get {
                return ((bool)(this["Search_hardware_WrittenOff"]));
            }
            set {
                this["Search_hardware_WrittenOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Search_hardware_JiraTask {
            get {
                return ((bool)(this["Search_hardware_JiraTask"]));
            }
            set {
                this["Search_hardware_JiraTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Search_hardware_Reason {
            get {
                return ((bool)(this["Search_hardware_Reason"]));
            }
            set {
                this["Search_hardware_Reason"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_mainTB_ID {
            get {
                return ((bool)(this["Search_mainTB_ID"]));
            }
            set {
                this["Search_mainTB_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_mainTB_date {
            get {
                return ((bool)(this["Search_mainTB_date"]));
            }
            set {
                this["Search_mainTB_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_mainTB_TypeAC {
            get {
                return ((bool)(this["Search_mainTB_TypeAC"]));
            }
            set {
                this["Search_mainTB_TypeAC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_mainTB_InvNum {
            get {
                return ((bool)(this["Search_mainTB_InvNum"]));
            }
            set {
                this["Search_mainTB_InvNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_mainTB_LanName {
            get {
                return ((bool)(this["Search_mainTB_LanName"]));
            }
            set {
                this["Search_mainTB_LanName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_mainTB_ResName {
            get {
                return ((bool)(this["Search_mainTB_ResName"]));
            }
            set {
                this["Search_mainTB_ResName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_mainTB_Room {
            get {
                return ((bool)(this["Search_mainTB_Room"]));
            }
            set {
                this["Search_mainTB_Room"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_mainTB_Floor {
            get {
                return ((bool)(this["Search_mainTB_Floor"]));
            }
            set {
                this["Search_mainTB_Floor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_mainTB_TypeDiv {
            get {
                return ((bool)(this["Search_mainTB_TypeDiv"]));
            }
            set {
                this["Search_mainTB_TypeDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_mainTB_SN {
            get {
                return ((bool)(this["Search_mainTB_SN"]));
            }
            set {
                this["Search_mainTB_SN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_mainTB_Model {
            get {
                return ((bool)(this["Search_mainTB_Model"]));
            }
            set {
                this["Search_mainTB_Model"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_mainTB_WrittenOff {
            get {
                return ((bool)(this["Search_mainTB_WrittenOff"]));
            }
            set {
                this["Search_mainTB_WrittenOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_mainTB_JiraTask {
            get {
                return ((bool)(this["Search_mainTB_JiraTask"]));
            }
            set {
                this["Search_mainTB_JiraTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Search_mainTB_Reason {
            get {
                return ((bool)(this["Search_mainTB_Reason"]));
            }
            set {
                this["Search_mainTB_Reason"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Search_stockroom_ID {
            get {
                return ((bool)(this["Search_stockroom_ID"]));
            }
            set {
                this["Search_stockroom_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Search_stockroom_date {
            get {
                return ((bool)(this["Search_stockroom_date"]));
            }
            set {
                this["Search_stockroom_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_stockroom_InvNum {
            get {
                return ((bool)(this["Search_stockroom_InvNum"]));
            }
            set {
                this["Search_stockroom_InvNum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_stockroom_Quantity {
            get {
                return ((bool)(this["Search_stockroom_Quantity"]));
            }
            set {
                this["Search_stockroom_Quantity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_stockroom_TypeDiv {
            get {
                return ((bool)(this["Search_stockroom_TypeDiv"]));
            }
            set {
                this["Search_stockroom_TypeDiv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Search_stockroom_SN {
            get {
                return ((bool)(this["Search_stockroom_SN"]));
            }
            set {
                this["Search_stockroom_SN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_stockroom_Model {
            get {
                return ((bool)(this["Search_stockroom_Model"]));
            }
            set {
                this["Search_stockroom_Model"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Search_stockroom_WrittenOff {
            get {
                return ((bool)(this["Search_stockroom_WrittenOff"]));
            }
            set {
                this["Search_stockroom_WrittenOff"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Search_stockroom_JiraTask {
            get {
                return ((bool)(this["Search_stockroom_JiraTask"]));
            }
            set {
                this["Search_stockroom_JiraTask"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Search_stockroom_Reason {
            get {
                return ((bool)(this["Search_stockroom_Reason"]));
            }
            set {
                this["Search_stockroom_Reason"] = value;
            }
        }
    }
}
